name: 自动爬取节点订阅

on:
  schedule:
    # 设置定时运行，这里设置为每天北京时间8点运行（对应UTC时间0点）
    - cron: '0 0 * * *'
  workflow_dispatch:
    # 允许从GitHub UI手动触发工作流

# 添加权限设置
permissions:
  contents: write  # 给予写入内容的权限

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: 创建必要的目录
        run: |
          mkdir -p results/{datiya,freev2,bestclash,shaoyou,ripao,v2rayc}
          mkdir -p downloads/{datiya,freev2,bestclash,shaoyou,ripao,v2rayc}
          mkdir -p web
      
      # 运行各种爬虫任务
      - name: 获取新日期节点数据
        run: python monitor_and_fetch.py
        
      - name: 爬取BestClash订阅
        run: python monitor_and_fetch.py --bestclash
        
      - name: 爬取FreeV2.net订阅
        run: python monitor_and_fetch.py --freev2
        
      - name: 爬取周润发公益v2ray节点
        run: python monitor_and_fetch.py --shaoyou
        
      - name: 爬取日日更新节点永久订阅
        run: python monitor_and_fetch.py --ripao
        
      - name: 爬取v2rayc.github.io节点订阅
        run: python monitor_and_fetch.py --v2rayc
        
      - name: 重新生成HTML页面
        run: python monitor_and_fetch.py --generate-html
        
      # 可选：上传生成的文件作为构建产物
      - name: 上传生成的数据和网页
        uses: actions/upload-artifact@v3
        with:
          name: scraped-data
          path: |
            web/
            results/
            downloads/
      
      # 提交更改回仓库
      - name: 配置Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
      
      - name: 提交更改
        run: |
          git add results/ downloads/ web/
          git commit -m "自动更新节点订阅数据 $(date +'%Y-%m-%d %H:%M:%S')" || echo "没有更改需要提交"
          git push 